# Generated by Django 3.2.9 on 2025-01-31 16:14

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to=users.models.profile_photo_path),
        ),
        migrations.AddField(
            model_name='instructor',
            name='rank',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
