# Generated by Django 3.2.9 on 2024-10-05 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0003_user_faculty"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=30, unique=True)),
                ("title", models.CharField(max_length=25)),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Saturday"),
                            (2, "Sunday"),
                            (3, "Monday"),
                            (4, "Tuesday"),
                            (5, "Wednesday"),
                            (6, "Thursday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.instructor",
                    ),
                ),
            ],
            options={
                "unique_together": {("day_of_week", "start_time", "end_time")},
            },
        ),
    ]
