name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: didar
          POSTGRES_PASSWORD: d1d2a3r
          POSTGRES_DB: didar
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U didar" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    env:
      SECRET_KEY: django-insecure-pg5qpxt=6kychycn8+%z8&qu9&##(c%ullqe-e4qvbb*@5j)6h
      POSTGRES_HOST: localhost
      POSTGRES_USER: didar
      POSTGRES_PASSWORD: d1d2a3r
      POSTGRES_DB: didar
      POSTGRES_PORT: 5432
      DJANGO_SETTINGS_MODULE: didar.settings.development

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Apply migrations
      run: |
        python manage.py migrate

    - name: Run tests
      run: |
        python manage.py test
